### ISSUE TITLE
Map is not being property cleanup

### ISSUE THREAD

**Issue by grillorafael** [commodityvectors/react-mapbox-gl#12]
A `.remove()` should be called within `componentWillUnmount` on the map in order to properly cleanup resources. At the moment if you render different maps through your use it will start growing memory usage by a lot. https://www.mapbox.com/mapbox-gl-js/api/#map#remove

https://github.com/commodityvectors/react-mapbox-gl/blob/master/src/Map.js#L154 -> It is enough to just call `.remove()` on the map.

At the moment, adding this makes some other components cleanup methods break since the map is being cleaned and they are trying to remove themselves.

**Comment by protetore** [comment]
It's fixed now
